name: CD

on:
  push:
    branches:
      - 'prod'
      - 'preprod'
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-3
    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}

      - run: sam build

      - name: Deploy application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ github.ref_name }}-geoserver-availability-checker --capabilities CAPABILITY_IAM --parameter-overrides Env=${{ github.ref_name }} --resolve-s3 --tags app=geoserver-availability-checker --resolve-image-repos
